# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/d/School/EDAF50 - C++/CppProject"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/d/School/EDAF50 - C++/CppProject"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/School/EDAF50 - C++/CppProject/CMakeFiles" "/mnt/d/School/EDAF50 - C++/CppProject/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/School/EDAF50 - C++/CppProject/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clientserver

# Build rule for target.
clientserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clientserver
.PHONY : clientserver

# fast build rule for target.
clientserver/fast:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/build
.PHONY : clientserver/fast

#=============================================================================
# Target rules for targets named main_disk

# Build rule for target.
main_disk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_disk
.PHONY : main_disk

# fast build rule for target.
main_disk/fast:
	$(MAKE) -f example/CMakeFiles/main_disk.dir/build.make example/CMakeFiles/main_disk.dir/build
.PHONY : main_disk/fast

#=============================================================================
# Target rules for targets named main_client

# Build rule for target.
main_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_client
.PHONY : main_client

# fast build rule for target.
main_client/fast:
	$(MAKE) -f example/CMakeFiles/main_client.dir/build.make example/CMakeFiles/main_client.dir/build
.PHONY : main_client/fast

#=============================================================================
# Target rules for targets named main_memory

# Build rule for target.
main_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_memory
.PHONY : main_memory

# fast build rule for target.
main_memory/fast:
	$(MAKE) -f example/CMakeFiles/main_memory.dir/build.make example/CMakeFiles/main_memory.dir/build
.PHONY : main_memory/fast

src/client.o: src/client.cc.o

.PHONY : src/client.o

# target to build an object file
src/client.cc.o:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/client.cc.o
.PHONY : src/client.cc.o

src/client.i: src/client.cc.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.cc.i:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/client.cc.i
.PHONY : src/client.cc.i

src/client.s: src/client.cc.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.cc.s:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/client.cc.s
.PHONY : src/client.cc.s

src/connection.o: src/connection.cc.o

.PHONY : src/connection.o

# target to build an object file
src/connection.cc.o:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/connection.cc.o
.PHONY : src/connection.cc.o

src/connection.i: src/connection.cc.i

.PHONY : src/connection.i

# target to preprocess a source file
src/connection.cc.i:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/connection.cc.i
.PHONY : src/connection.cc.i

src/connection.s: src/connection.cc.s

.PHONY : src/connection.s

# target to generate assembly for a file
src/connection.cc.s:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/connection.cc.s
.PHONY : src/connection.cc.s

src/disk_db.o: src/disk_db.cc.o

.PHONY : src/disk_db.o

# target to build an object file
src/disk_db.cc.o:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/disk_db.cc.o
.PHONY : src/disk_db.cc.o

src/disk_db.i: src/disk_db.cc.i

.PHONY : src/disk_db.i

# target to preprocess a source file
src/disk_db.cc.i:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/disk_db.cc.i
.PHONY : src/disk_db.cc.i

src/disk_db.s: src/disk_db.cc.s

.PHONY : src/disk_db.s

# target to generate assembly for a file
src/disk_db.cc.s:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/disk_db.cc.s
.PHONY : src/disk_db.cc.s

src/memory_db.o: src/memory_db.cc.o

.PHONY : src/memory_db.o

# target to build an object file
src/memory_db.cc.o:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/memory_db.cc.o
.PHONY : src/memory_db.cc.o

src/memory_db.i: src/memory_db.cc.i

.PHONY : src/memory_db.i

# target to preprocess a source file
src/memory_db.cc.i:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/memory_db.cc.i
.PHONY : src/memory_db.cc.i

src/memory_db.s: src/memory_db.cc.s

.PHONY : src/memory_db.s

# target to generate assembly for a file
src/memory_db.cc.s:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/memory_db.cc.s
.PHONY : src/memory_db.cc.s

src/message_handler.o: src/message_handler.cc.o

.PHONY : src/message_handler.o

# target to build an object file
src/message_handler.cc.o:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/message_handler.cc.o
.PHONY : src/message_handler.cc.o

src/message_handler.i: src/message_handler.cc.i

.PHONY : src/message_handler.i

# target to preprocess a source file
src/message_handler.cc.i:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/message_handler.cc.i
.PHONY : src/message_handler.cc.i

src/message_handler.s: src/message_handler.cc.s

.PHONY : src/message_handler.s

# target to generate assembly for a file
src/message_handler.cc.s:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/message_handler.cc.s
.PHONY : src/message_handler.cc.s

src/ourserver.o: src/ourserver.cc.o

.PHONY : src/ourserver.o

# target to build an object file
src/ourserver.cc.o:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/ourserver.cc.o
.PHONY : src/ourserver.cc.o

src/ourserver.i: src/ourserver.cc.i

.PHONY : src/ourserver.i

# target to preprocess a source file
src/ourserver.cc.i:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/ourserver.cc.i
.PHONY : src/ourserver.cc.i

src/ourserver.s: src/ourserver.cc.s

.PHONY : src/ourserver.s

# target to generate assembly for a file
src/ourserver.cc.s:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/ourserver.cc.s
.PHONY : src/ourserver.cc.s

src/server.o: src/server.cc.o

.PHONY : src/server.o

# target to build an object file
src/server.cc.o:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/server.cc.o
.PHONY : src/server.cc.o

src/server.i: src/server.cc.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.cc.i:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/server.cc.i
.PHONY : src/server.cc.i

src/server.s: src/server.cc.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.cc.s:
	$(MAKE) -f CMakeFiles/clientserver.dir/build.make CMakeFiles/clientserver.dir/src/server.cc.s
.PHONY : src/server.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... clientserver"
	@echo "... main_disk"
	@echo "... main_client"
	@echo "... main_memory"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/connection.o"
	@echo "... src/connection.i"
	@echo "... src/connection.s"
	@echo "... src/disk_db.o"
	@echo "... src/disk_db.i"
	@echo "... src/disk_db.s"
	@echo "... src/memory_db.o"
	@echo "... src/memory_db.i"
	@echo "... src/memory_db.s"
	@echo "... src/message_handler.o"
	@echo "... src/message_handler.i"
	@echo "... src/message_handler.s"
	@echo "... src/ourserver.o"
	@echo "... src/ourserver.i"
	@echo "... src/ourserver.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

